[workspace]

[dev-dependencies]
cucumber = "0.19"
futures = "0.3"
tokio = { version = "1.26.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }

[[test]]
name = "contract" 
harness = false

members = [
    "crates/pubnub",

    # Internal crates
    "crates/contract-tests",
    "examples/",
]
