[package]
name = "pubnub"
version = "0.0.0"
edition = "2021"
license = "MIT"
authors = ["PubNub <support@pubnub.com>"]
description = "PubNub SDK for Rust"
repository = "https://github.com/pubnub/rust"
documentation = "https://docs.rs/pubnub" # TODO: add docs and connect with pubnub docs
homepage = "https://www.pubnub.com"
categories = ["api-bindings", "asynchronous", "network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.12"
async-trait = "0.1"
log = "0.4"
uuid = { version = "1.3", features = ["v4"] }
urlencoding = "2.1.2"
base64 = "0.21"
hashbrown = "0.13"

# signature
hmac = "0.12"
sha2 = "0.10"
time = { version = "0.3", features = ["alloc"] }

# serde
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

# reqwest
reqwest = { version = "0.11", optional = true }

# crypto
aes = { version = "0.8.2", optional = true }
cbc = { version = "0.1.2", optional = true }
rand = { version = "0.8.5", optional = true }

# parse_token
ciborium = { git = "https://github.com/enarx/ciborium.git", rev = "dc9d27d", optional = true }
spin = "0.9"
snafu = "0.7"

[dev-dependencies]
async-trait = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
wiremock = "0.5"
env_logger = "0.10"
cucumber = { version = "0.19", features = ["output-junit"] }
futures = "0.3"
reqwest = { version = "0.11", features = ["json"] }
test-case = "3.0"
hashbrown = { version = "0.13", features = ["serde"] }

[[test]]
name = "contract_test"
harness = false
required-features = ["contract_test"]

[features]
full = ["serde", "reqwest", "aescbc", "parse_token", "std"]
default = ["serde", "reqwest", "aescbc", "std"]
serde = ["dep:serde", "dep:serde_json"]
reqwest = ["dep:reqwest"]
aescbc = ["dep:aes", "dep:cbc", "dep:rand"]
contract_test = []
parse_token = ["dep:ciborium"]
std = []

[[example]]
name = "publish"
required-features = ["default"]

