name: Cargo-Deny

on: 
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  cargo-deny:
    name: Check Cargo crate dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v1
      with:
        command: check ${{ matrix.checks }}
  all-cargo-deny:
    name: Tests
    runs-on: ubuntu-latest
    needs: [cargo-deny]
    steps:
      - name: Tests summary
        run: echo -e "\033[38;2;95;215;0m\033[1mAll Deny check successfully passed"
