name: Vulnerability scan
on:
  push:
    branches:
      - snyk-integration-test
      - master
      - main

jobs:
  security:
    runs-on:
      group: organization/Default
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Snyk CLI
        id: snyk
        uses: snyk/actions/setup@master
        with:
          snyk-version: 1.1297.1
      - name: Setup Snyk CLI dependencies
        uses: actions/setup-go@v1
        with:
          go-version: "1.13"
      - name: Installed Snyk version
        run: echo "${{ steps.snyk.outputs.version }}"
      - name: Install cargo-cyclonedx
        run: cargo install cargo-cyclonedx
      - name: Create CycloneDX SBOM
        run: cargo cyclonedx --all-features --format json --spec-version 1.5
      - name: Run Snyk monitor for vulnerabilities
        run: |
          snyk sbom monitor --org=sdk --experimental --file=pubnub.cdx.json --project-name=pubnub/rust
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_SDK_TOKEN }}